variables:

image: bowmanhan/node-chrome:latest

cache:
  paths:
  - node_modules/
stages:
- test
- build


dev_test:
  stage: test
  environment: dev
  script:
  - yarn install
  - yarn test

build:
  stage: build
  environment: production
  artifacts:
    paths:
    - build/
  script:
  - yarn install
  - yarn build
