variables:

image: bowmanhan/node:10.11.0-alpine

cache:
  paths:
  - node_modules/
stages:
- test
- deploy


dev_test:
  stage: test
  environment: dev
  only:
  - dev
  script:
  - yarn install
  - yarn test

deploy_production:
  stage: deploy
  environment: production
  only:
  - master
  artifacts:
    paths:
    - dist/
  script:
  - yarn install
  - yarn postbuild
  - cd build/
  - sshpass -V
  - export SSHPASS=$USER_PASS
  - sshpass -e scp  -o stricthostkeychecking=no -r . root@97.64.18.168:/var/www/pomometer/
