variables:

image: bowmanhan/node:10.11.0-alpine

cache:
  paths:
  - node_modules/
stages:
- test


dev_test:
  stage: test
  environment: dev
  only:
  - dev
  script:
  - yarn install
  - yarn test
